"""empty message

Revision ID: 73540f8d96a5
Revises: 1fe1f23e7dbd
Create Date: 2019-06-22 08:05:10.600796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73540f8d96a5'
down_revision = '1fe1f23e7dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('venue_address', sa.String(length=45), nullable=False))
    op.add_column('tours', sa.Column('venue_city', sa.String(length=45), nullable=False))
    op.add_column('tours', sa.Column('venue_country', sa.String(length=45), nullable=False))
    op.add_column('tours', sa.Column('venue_phone', sa.String(length=45), nullable=False))
    op.drop_constraint(None, 'tours', type_='foreignkey')
    op.drop_constraint(None, 'tours', type_='foreignkey')
    op.drop_column('tours', 'fkey_tour_address_id')
    op.drop_column('tours', 'fkey_tour_user_id')
    op.add_column('users', sa.Column('fkey_user_address_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'addresses', ['fkey_user_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'fkey_user_address_id')
    op.add_column('tours', sa.Column('fkey_tour_user_id', sa.INTEGER(), nullable=False))
    op.add_column('tours', sa.Column('fkey_tour_address_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'tours', 'users', ['fkey_tour_user_id'], ['id'])
    op.create_foreign_key(None, 'tours', 'addresses', ['fkey_tour_address_id'], ['id'])
    op.drop_column('tours', 'venue_phone')
    op.drop_column('tours', 'venue_country')
    op.drop_column('tours', 'venue_city')
    op.drop_column('tours', 'venue_address')
    # ### end Alembic commands ###
